refactor:重构Outline模块
X重构Outline模块：
    XLaTeX与Markdown回归测试
    XOutline需要支持横向与纵向两种布局形式
    X*帮助vue-tree修复bug*
    X解耦Outline以及相关工具的算法与逻辑代码，对于Markdown和LaTeX来说，是对同一个接口的两套适配；
    XMarkdown目前可以直接与Outline双向映射，以及多层级的这种映射；LaTeX也需要实现这样的功能，而且需要保证原先的注释、还有一些控制信息，例如宏包、注释等文本内容之外的文字，不会因为相互映射而有任何改变。
       XLaTeX也需要能和大纲树相互转换（包括一些必要的metadata，控制信息，与文章无关的文字，注释等等信息，也可以相互映射，也就是说大纲树是要有地方存这些内容的。可以是每个节点里面有存这些的地方，也可以是整个LaTeX文档统一存，看哪一种更方便，更贴合实际），实现类似于extractOutlineTreeFromMarkdown,generateMarkdownFromOutlineTree这样的方法，参考md-utils.js；latex的方法写在latex-utils.js里面
       X一些Outline相关的AI工具的提示词，schema，也要对这两种文档语言做相应的适配、解耦
       X最终的效果是LaTeX文档也可以和Markdown在Outline界面有完全相同的使用预期行为
            Xerror: __temp_compile_1763312980027.tex:486: Missing endcsname inserted

    X除此之外对于大纲树这个组件，要支持拖拽功能，当按住节点拖拽时，就可以进入拖拽状态，灵活地调整文章的结构
    X除此之外，Outline.vue，日志Console的下端没有考虑到底部状态栏，会被底部状态栏给覆盖，这个也是有问题的，参考一下编辑器界面的排版布局
    XOutline AI任务取消按钮